# Generated by Django 5.1.5 on 2025-01-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_books_user_message_books_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"ordering": ["updated", "created"]},
        ),
        migrations.AddField(
            model_name="books",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
