# Generated by Django 5.1.5 on 2025-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_rename_series_books_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="books",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
