# Generated by Django 5.1.5 on 2025-01-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_books_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="books/pdfs/"),
        ),
    ]
